name: Upload

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push Kaggle Kernel
        uses: Elesdes/DeepLearning4IABD@dev
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id: ${{ secrets.KAGGLE_USERNAME }}/${{ github.sha }}
          title: ${{ github.sha }}
          code_file: ./notebook.ipynb
          language: python
          kernel_type: notebook
          is_private: true
          competition_sources: goodreads-books-reviews-290312